name: qnetvo-dev
channels:
  - defaults
dependencies:
  - python=3.11
  - sphinx
  - black
  - pytest
  - notebook
  - matplotlib
  - pip
  - pip:
    - -r requirements.txt
    - -r docs/requirements.txt
