name: qnetvo-dev
channels:
  - defaults
dependencies:
  - python=3.8
  - black
  - sphinx
  - pytest
  - notebook
  - matplotlib
  - pip
  - pip:
    - -r requirements.txt
    - furo
    - m2r2==0.3.2
    - sphinxcontrib-email==0.1
