name: Check Documentation
on: 
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r docs/requirements.txt
      - name: Build Documentation
        run: |
          sphinx-build -b html docs/source/ docs/build/html
